config/routes.rb
Rails.application.routes.draw do

  resources :tasks

authenticated :user do
    root to: 'tasks#index', as: :authenticated_root
  end

devise_for :users

  get 'task_new' => "tasks#new"
  get 'task_index' => "tasks#index"

  get 'users/show'

  get 'main/index'

  get 'contact' => 'main#contact'

  root 'main#index'

  get 'main' => 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

#  def log_in_action
      #  redirect_to users_show_path
  # end



end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def index
  end

  def contact
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]


  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reloaded
    respond_to do |format|
      if @task.reloaded(task_params)
        format.html { redirect_to task_index, notice: 'Task was successfully Updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :user_id, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 #before_action :log_in_action

 def index
   @currentUser = current_user.id
 end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="nav">



  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocitoff", main_path %></li>
      <li><%= link_to "Profile", task_index_path(@task) %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "New Task", task_new_path %></li>
<div class="connexion" style="float:right">
      <% if user_signed_in? %>
  Signed in as: <strong><%= current_user.email %></strong> |
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
  <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</div>

</div>
</header>

<div>
    <%= yield %>
</div>

</body>
</html>

app/views/main/contact.html.erb
<h1>Main#contact</h1>
<p>Find me in app/views/main/contact.html.erb</p>

app/views/main/index.html.erb
<h1>Blocitoff</h1>
<p>Create - Realise - Delete</p>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :task_name %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :task_user_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status, id: :task_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to "Back", task_index_path(@task) %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users <%= current_user.email%></h1>
<p>This is your profile</p>
<p>this is your ID: <b><%= current_user.id %></b></p>


<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Status</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.user.email %></td>Back
        <td><% if task.status == true %>
            This task has been realised
            <% elsif task.status == false %>
          You must do it
          <%end%></td>

<td><%= "#{distance_of_time_in_words(task.created_at + 7.days, Time.now, include_seconds: false)} left" %></td>
        <td>
          <div class="field">
            <%= form_with(model: task, local: true) do |form| %>
            <% if task.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

                <ul>
                <% task.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <%= form.check_box :status, id: :task_status %>
            <td><div class="actions">
              <%= form.submit %></td>
<%end%>

          </div></td>
          <td><%= link_to 'Edit', edit_task_path(task) %></td>
          <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>

          </div>
</tr>

<%end%>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user.email %>
</p>
  <strong>Date:</strong>
  <p><%= "Created the #{@task.created_at.strftime("%m-%d-%Y")}" %></p>
  <p><%= "#{distance_of_time_in_words(@task.created_at + 7.days, Time.now, include_seconds: false)} left." %>
  <% if @task.created_at < @task.created_at - 6.days %>
     <p>NOOOOOOOOOOOOOOOOOOOOOO RUUUSH</p>
    <% else %>
    <p>Chill out - Take your time </p>
    <%end%></p>
<p>
  <strong>Status:</strong>
  <% if @task.status == true %>
    This task has been realised
    <% elsif @task.status == false %>
  You must do it
  <%end%>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', task_index_path(@task) %>

app/views/users/show.html.erb
<h1>Users <%= current_user.email%></h1>
This is your profile